package by.silebin.final_project.command;

public enum CommandType {
    GO_TO_LOGIN,
    GO_TO_COCKTAILS_LIST,
    GO_TO_ADD_COCKTAIL,
    GO_TO_REGISTER,
    LOGIN_USER,
    REGISTER_USER,
    RATE_USER,
    LOGOUT_USER,
    COCKTAIL_INFO,
    ADD_COCKTAIL,
    LEAVE_COMMENT,
    PROFILE,
    CHANGE_LOCALE,
    UNAPPROVED_COCKTAILS,
    APPROVE_COCKTAIL,
    DELETE_COMMENT,
    USERS_STAT,
    DELETE_COCKTAIL,
    CHANGE_USER_ROLE,
    EDIT_COCKTAIL,
    EDIT_USER,
    SAVE_COCKTAIL,
    DEFAULT
}
